apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: "12345"
spec:
  selector:
   app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
    - protocol: TCP
      name: external
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: phpmyadmin_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: wordpress
