# ---
# apiVersion: apps/v1
# kind: DaemonSet
# metadata:
#   name: telegraf
#   labels:
#     app: telegraf
# spec:
#   selector:
#     matchLabels:
#       app: telegraf
#   template:
#     metadata:
#       labels:
#         app: telegraf
#     spec:
#       containers:
#       - name: telegraf
#         image: telegraf_image
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 8125
#         volumeMounts:
#         - name: docker-socket
#           mountPath: /var/run/docker.sock
#       volumes:
#       - name: docker-socket
#         hostPath:
#           path: /var/run/docker.sock
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
spec:
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  minReadySeconds: 5
  template:
    metadata:
      name: telegraf
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf_image
          imagePullPolicy: Never
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket

