apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: "12345"
spec:
  selector:
   app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  ports:
  - port: 20
    name: ftp-data
    targetPort: 20
  - port: 21
    name: ftp-control
    targetPort: 21
  - port: 64000
    name: ftp-passive
    targetPort: 64000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 64000